### ISSUE TITLE
не красивый вывод в консоли

### ISSUE THREAD

**Issue by ilnurgi** [Rinatgi/zadachnik#1]
Выбирите необходимое действие: 

```
                0.Выход.

                1.Добавить заметку. 

                2.Посмотреть список всех задач. 

                3.Список выполненных задач. 

                4.Список будущих задач. 

                5.Удалить заметку. 

                6.Изменить задачу.
```

Выбирите значение 1
Введите новую задачу: Купить хлеб машину дом ещё машину
Введите дату начала выполнения задачи (год.месяц.число):
 2016.1.1
Введите дату завершения задачи (год.месяц.число):
2016.1.2

---
1. опечатки русского языка, Выбирите
2. перед датой начала лишний пробел

**Comment by ilnurgi** [comment]
python zametki.py 

Выберите необходимое действие: 

```
                0.Выход.

                1.Добавить заметку. 

                2.Посмотреть список всех задач. 

                3.Список выполненных задач. 

                4.Список будущих задач. 

                5.Удалить заметку. 

                6.Изменить задачу.
```

Выберите значение 1
Traceback (most recent call last):
  File "zametki.py", line 230, in <module>
    main()
  File "zametki.py", line 54, in main
    new_note()
  File "zametki.py", line 82, in new_note
    new_target = raw_input(u'Введите новую задачу: '.decode('utf-8'))
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)
